"""
assembler.py -- Step 5 of the migration pipeline.

Takes:
  - the LLM extraction result (strict JSON matching workflow_extraction.schema.json)
  - the source project.yaml (for name/description/subagents)
  - the scaffold report (for warnings)

Produces:
  - a fully-formed project.yaml string, with # TODO markers next to any field
    the LLM flagged as low-confidence or ambiguous.

No LLM calls here. The LLM never writes YAML directly -- it returns JSON and
this module deterministically renders YAML.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from tools.migrate.extractor import ExtractionResult


# ---------------------------------------------------------------------------
# Confidence thresholds -- below these we emit a # TODO comment.
# ---------------------------------------------------------------------------

CONFIDENCE_TODO_THRESHOLD = 0.7


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------

@dataclass
class AssemblyResult:
    yaml_text:      str
    todo_markers:   list[str] = field(default_factory=list)   # human-readable summary
    source_name:    str = ""
    pattern:        str = ""


class AssemblerError(RuntimeError):
    pass


# ---------------------------------------------------------------------------
# Assembler
# ---------------------------------------------------------------------------

class Assembler:
    """Deterministic extraction-JSON -> project.yaml renderer."""

    def __init__(self, extraction: ExtractionResult, source_yaml_path: Path):
        self.extraction = extraction
        self.source_yaml = self._load_source(source_yaml_path)
        self.todos: list[str] = []

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def assemble(self) -> AssemblyResult:
        pattern = self.extraction.pattern

        if pattern == "unknown":
            # Fall through anyway; caller decides what to do with the TODOs.
            self.todos.append(
                "pattern=unknown: LLM could not confidently classify the workflow. "
                "Review the workflow block manually."
            )

        parts: list[str] = []
        parts.append(self._render_header())
        parts.append(self._render_metadata())
        parts.append(self._render_subagents())
        parts.append(self._render_workflow())
        parts.append(self._render_footer_notes())

        yaml_text = "\n".join(p.rstrip() for p in parts if p) + "\n"

        return AssemblyResult(
            yaml_text=yaml_text,
            todo_markers=self.todos,
            source_name=self.source_yaml.get("name", ""),
            pattern=pattern,
        )

    # ------------------------------------------------------------------
    # Sections
    # ------------------------------------------------------------------

    def _render_header(self) -> str:
        name = self.source_yaml.get("name", "migrated-project")
        return (
            "# =============================================================================\n"
            f"# {name} -- migrated to claude-cli-orchestrator\n"
            "# =============================================================================\n"
            "# This file was generated by tools.migrate from an AgentWeave project.\n"
            f"# Extraction confidence: {self.extraction.confidence:.2f}"
            f"  |  pattern: {self.extraction.pattern}\n"
            "# Any `# TODO` comments below mark fields that need human review.\n"
            "# ============================================================================="
        )

    def _render_metadata(self) -> str:
        src = self.source_yaml
        name         = src.get("name") or "migrated-project"
        display      = src.get("display_name") or name
        description  = src.get("description") or ""

        lines = [
            f"name: {name}",
            f'display_name: "{self._esc(display)}"',
            f'description: "{self._esc(description)}"',
        ]
        return "\n".join(lines)

    def _render_subagents(self) -> str:
        """
        Preserve the source subagents block but normalize two things:
          1. prompt_file: prefix with "agents/" if not already
          2. tools: expand inline [a, b, c] into a YAML list
        """
        subs = self.source_yaml.get("subagents") or []
        if not subs:
            raise AssemblerError("Source project.yaml has no 'subagents' block.")

        out = ["subagents:"]
        for sub in subs:
            name   = sub.get("name", "")
            pfile  = sub.get("prompt_file", "")
            if pfile and not pfile.startswith("agents/"):
                pfile = f"agents/{pfile}"
            desc   = sub.get("description", "") or ""
            model  = sub.get("model", "haiku") or "haiku"
            tools  = sub.get("tools", []) or []

            out.append(f"  - name: {name}")
            out.append(f"    prompt_file: {pfile}")
            if desc:
                out.append(f'    description: "{self._esc(desc)}"')
            out.append(f"    model: {model}")
            if tools:
                out.append("    tools:")
                for t in tools:
                    out.append(f"      - {t}")
            out.append("")
        return "\n".join(out)

    def _render_workflow(self) -> str:
        data     = self.extraction.data
        pattern  = data.get("pattern", "unknown")

        lines = ["workflow:"]

        if pattern == "A":
            lines.extend(self._render_pattern_a(data))
        elif pattern == "B":
            lines.extend(self._render_pattern_b(data))
        elif pattern == "C":
            lines.extend(self._render_pattern_c(data))
        else:
            lines.append("  # TODO: pattern=unknown. Fill in manually.")
            lines.extend(self._render_steps_bare(data))

        lines.append("")
        lines.extend(self._render_passthrough(data))

        return "\n".join(lines)

    # ------- Pattern renderers --------

    def _render_pattern_a(self, data: dict) -> list[str]:
        lines = []
        lines.append("  # Pattern A: single agent, no retry loop")
        lines.append("  steps:")
        for step in data.get("steps", []):
            lines.extend(self._render_step_basic(step, indent="    "))
        return lines

    def _render_pattern_b(self, data: dict) -> list[str]:
        lines = []
        lines.append("  # Pattern B: pipeline-level retry loop with feedback")

        max_iter = data.get("max_iterations")
        if max_iter is None:
            lines.append("  # TODO: max_iterations not extracted; review")
            self.todos.append("workflow.max_iterations could not be determined")
            max_iter = 3
        lines.append(f"  max_iterations: {max_iter}")
        lines.append("")
        lines.append("  steps:")
        for step in data.get("steps", []):
            lines.extend(self._render_step_basic(step, indent="    "))

        lines.append("")
        lines.extend(self._render_pipeline_exit_condition(data))

        lines.append("")
        lines.extend(self._render_pipeline_feedback(data))
        return lines

    def _render_pattern_c(self, data: dict) -> list[str]:
        lines = []
        lines.append("  # Pattern C: step-level independent retries")
        lines.append("  steps:")
        for step in data.get("steps", []):
            lines.extend(self._render_step_with_retry(step, indent="    "))
        return lines

    def _render_steps_bare(self, data: dict) -> list[str]:
        lines = ["  steps:"]
        for step in data.get("steps", []):
            lines.extend(self._render_step_basic(step, indent="    "))
        return lines

    # ------- Step primitives --------

    def _render_step_basic(self, step: dict, indent: str) -> list[str]:
        """Used for pattern A and B steps (no per-step retry)."""
        out = []
        sid = step.get("id") or step.get("agent")
        agent = step.get("agent") or sid
        conf = float(step.get("confidence", 1.0))

        out.append(f"{indent}- id: {sid}")
        out.append(f"{indent}  agent: {agent}")

        deps = step.get("depends_on") or []
        if deps:
            dep_list = ", ".join(deps)
            out.append(f"{indent}  depends_on: [{dep_list}]")

        if conf < CONFIDENCE_TODO_THRESHOLD:
            out.append(f"{indent}  # TODO: low-confidence extraction (confidence={conf:.2f})")
            self.todos.append(f"step '{sid}' extracted with confidence={conf:.2f}")

        return out

    def _render_step_with_retry(self, step: dict, indent: str) -> list[str]:
        """Used for pattern C steps (each has max_retries + exit_condition)."""
        out = self._render_step_basic(step, indent)

        mr = step.get("max_retries")
        if mr is None:
            out.append(f"{indent}  # TODO: max_retries not extracted")
            self.todos.append(f"step '{step.get('id')}' missing max_retries")
            mr = 3
        out.append(f"{indent}  max_retries: {mr}")

        ec = step.get("exit_condition")
        if ec is None:
            out.append(f"{indent}  # TODO: exit_condition not extracted")
            self.todos.append(f"step '{step.get('id')}' missing exit_condition")
        else:
            out.append(f"{indent}  exit_condition:")
            out.append(f"{indent}    field: {ec.get('field', '')}")
            eq = ec.get("equals")
            out.append(f'{indent}    equals: "{self._esc(str(eq))}"')

        fb = step.get("feedback_field")
        if fb:
            out.append(f"{indent}  feedback:")
            out.append(f"{indent}    field: {fb}")
        else:
            out.append(f"{indent}  # TODO: feedback field not extracted")
            self.todos.append(f"step '{step.get('id')}' missing feedback field")

        return out

    # ------- Pipeline blocks --------

    def _render_pipeline_exit_condition(self, data: dict) -> list[str]:
        ec = data.get("pipeline_exit_condition")
        if not ec:
            self.todos.append("pipeline_exit_condition missing")
            return [
                "  # TODO: pipeline_exit_condition not extracted; fill in manually",
                "  exit_condition:",
                "    step: reviewer  # TODO",
                "    field: overall_status  # TODO",
                '    equals: "PASS"  # TODO',
            ]
        return [
            "  exit_condition:",
            f"    step: {ec.get('step', '')}",
            f"    field: {ec.get('field', '')}",
            f'    equals: "{self._esc(str(ec.get("equals", "")))}"',
        ]

    def _render_pipeline_feedback(self, data: dict) -> list[str]:
        fb = data.get("pipeline_feedback")
        if not fb:
            self.todos.append("pipeline_feedback missing")
            return [
                "  # TODO: pipeline_feedback not extracted; fill in manually",
                "  feedback:",
                "    - when:",
                "        step: reviewer  # TODO",
                "        field: overall_status  # TODO",
                '        not_equals: "PASS"',
                "      from:",
                "        step: reviewer  # TODO",
                "        field: feedback_for_generator  # TODO",
                "      to:",
                "        step: generator  # TODO",
                "        as: ctx_feedback",
                "      fallback: generic_validation_feedback",
            ]

        out = [
            "  feedback:",
            "    - when:",
            f"        step: {fb.get('from_step', '')}",
        ]

        # Try to reuse the exit-condition field as the 'when' predicate.
        ec = data.get("pipeline_exit_condition") or {}
        when_field  = ec.get("field", "overall_status")
        when_equals = ec.get("equals", "PASS")
        out.append(f"        field: {when_field}")
        out.append(f'        not_equals: "{self._esc(str(when_equals))}"')

        out.extend([
            "      from:",
            f"        step: {fb.get('from_step', '')}",
            f"        field: {fb.get('from_field', '')}",
            "      to:",
            f"        step: {fb.get('to_step', '')}",
            f"        as: {fb.get('as', 'ctx_feedback')}",
        ])
        fallback = fb.get("fallback")
        if fallback:
            out.append(f"      fallback: {fallback}")
        return out

    # ------- Passthrough --------

    def _render_passthrough(self, data: dict) -> list[str]:
        fields = data.get("passthrough_fields") or []
        conf   = float(data.get("passthrough_confidence", 0.0))

        if not fields:
            self.todos.append(
                "passthrough_fields is empty -- supervisor either explicitly "
                "declared no pass-through, or the LLM could not infer any."
            )
            return [
                "  # Developer can add input fields here that should be copied",
                "  # from input.json to output.json unchanged.",
                "  passthrough_fields: []",
            ]

        out = []
        if conf < CONFIDENCE_TODO_THRESHOLD:
            out.append(
                f"  # TODO: passthrough_fields extracted with low confidence ({conf:.2f});"
                " review and trim"
            )
            self.todos.append(
                f"passthrough_fields low confidence ({conf:.2f}); review the list"
            )
        out.append("  passthrough_fields:")
        for f in fields:
            out.append(f"    - {f}")
        return out

    # ------- Footer --------

    def _render_footer_notes(self) -> str:
        notes = self.extraction.notes or []
        if not notes:
            return ""
        lines = ["", "# Notes from the migration extractor:"]
        for n in notes:
            lines.append(f"#  - {n}")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _esc(s: str) -> str:
        return (s or "").replace('"', '\\"').replace("\n", " ").strip()

    @staticmethod
    def _load_source(path: Path) -> dict[str, Any]:
        with path.open("r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
